### PR TITLE
ARCH-1009 - Adding codenames to each of the workflows.

### PR DESCRIPTION
**Pull request by danielle-casella-adams**

### CODE REVIEW

**Review by JosephDSchwartz — APPROVED** [review]
I think ZestyFlamingo is my favorite, but it's hard to pick just one 😆

**Comment by hpractv** [comment]
So some have `_v1` Are we only going to add ad version piece after we increment?

**Comment by danielle-casella-adams** [comment]
InstaneHamster is my favorite.

**Comment by danielle-casella-adams** [comment]
It looks like two were missing this _v1.  I'll push that change up.

**Review by hpractv — APPROVED** [review]
👍🏽

**Pull request merged**
