### PR TITLE
SRE-208 - Updating workflow to output NEXT_RELEASE_VERSION.

### PR DESCRIPTION
**Pull request by jsclifford**
- Added outputs `NEXT_RELEASE_VERSION` and `NEXT_RELEASE_VERSION_NO_PREFIX`.  
- Updating to latest git-version-lite action

### CODE REVIEW

**Review by mike-schenk — CHANGES_REQUESTED** [review]
I don't think we should be committing package.json version numbers to the repo since we determine version numbers during our builds. My reasons are basically the same as what's [documented by semantic-release here](https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package.jsons-version-not-updated-in-my-repository).

`start-project` is an example where the package version is not committed to source control: https://github.com/im-practices/start-project/blob/main/src/start-project/package.json

If there's another reason we need these outputs, I'll listen.

But regardless, I don't think it's worth running git-version-lite _twice_ every time this reusable workflow is used when a very small subset of usages need the extra output.

As an alternative, we could expand git-version-lite itself to output the additional values directly.

**Comment by jsclifford** [comment]
Ok I will update the action to output both versions in git-version lite.

**Comment by jsclifford** [comment]
I updated git-version-lite to output the bare versions.  https://github.com/im-open/git-version-lite/pull/49 please review.  Once merged I will update this workflow.

**Comment by jsclifford** [comment]
@mike-schenk  please review pull request.  I have updated code per your request in your comments

**Review by mike-schenk — APPROVED** [review]

**Pull request merged**
